### PR TITLE
feat: support when text/event-stream is not the only content-type

### PR DESCRIPTION
**Pull request by dbuades**
First of all, thank you for this package, it is very useful !

I'm opening this PR to tackle an issue when using this package to consume events sent by the [Nvidia Triton Inference Server Generate Extension](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/protocol/extension_generate.html).

The extension uses `application/json, text/event-stream; charset=utf-8` as `content_type`, and thus, the method `_check_content_type()` was failing. By checking if `text/event-stream` is contained in the string, the issue is resolved.

### CODE REVIEW

**Comment by dbuades** [comment]
I'll close this PR seeing that it has been implemented on https://github.com/florimondmanca/httpx-sse/commit/0b5e9fdb91aa15e782c6643e77e67bb39cdec289

**Comment by florimondmanca** [comment]
Hi @dbuades 

Thanks for your contribution. This change looks good to me. Could we add an extra test against a content type like the one you're working with?

**Comment by florimondmanca** [comment]
@dbuades I just merged #22 which is this plus an additional test, and credited you as a co-author. Will release soon. Thanks!

**Comment by dbuades** [comment]
> @dbuades I just merged #22 which is this plus an additional test, and credited you as a co-author. Will release soon. Thanks!

Oh! I'm very sorry @florimondmanca, I missed this last message.

Thank you for your work!

**Pull request closed without merging**
